//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VST_sprava_servisu
{
    using System;
    using System.Collections.Generic;
    
    public partial class KategoriePoruchy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KategoriePoruchy()
        {
            this.Porucha = new HashSet<Porucha>();
        }
    
        public int Id { get; set; }
        public string NazevKategorie { get; set; }
        public bool OpravnenaReklamace { get; set; }
        public bool NeopravnenaReklamace { get; set; }
        public bool ReklamaceServisniZasah { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Porucha> Porucha { get; set; }
    }
}
