//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VST_sprava_servisu
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KontakniOsoba
    {
        public int Id { get; set; }
        [Display(Name = "Zákazník")]
        public int ZakaznikId { get; set; }
        [Display(Name = "Pøíjmení a jméno")]
        public string JmenoPrijmeni { get; set; }
        [Display(Name = "Pozice")]
        public string Pozice { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public Nullable<int> SAPId { get; set; }
        [Display(Name = "Provoz")]
        public Nullable<int> ProvozId { get; set; }
    
        public virtual Provoz Provoz { get; set; }
        public virtual Zakaznik Zakaznik { get; set; }
    }
}
