//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VST_sprava_servisu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Zakaznik> Zakaznik { get; set; }
        public virtual DbSet<Jazyk> Jazyk { get; set; }
        public virtual DbSet<Provoz> Provoz { get; set; }
        public virtual DbSet<Umisteni> Umisteni { get; set; }
    }
}
