//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VST_sprava_servisu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Porucha
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Porucha()
        {
            this.ServisniZasahPrvek = new HashSet<ServisniZasahPrvek>();
        }
    
        public int Id { get; set; }
        public string NazevPoruchy { get; set; }
        public int KategoriePoruchyId { get; set; }
        public bool SIL { get; set; }
        public Nullable<int> SkupinaArtikluId { get; set; }
    
        public virtual KategoriePoruchy KategoriePoruchy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServisniZasahPrvek> ServisniZasahPrvek { get; set; }
        public virtual SkupinaArtiklu SkupinaArtiklu { get; set; }
    }
}
