//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VST_sprava_servisu
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevizeSC
    {
        public int Id { get; set; }
        public int RevizeId { get; set; }
        public int SCProvozuId { get; set; }
        public string StavKoroze { get; set; }
        public string StavZnecisteni { get; set; }
        public string JineZavady { get; set; }
        public Nullable<int> UmisteniId { get; set; }
        public bool Baterie { get; set; }
        public bool Pyro { get; set; }
        public bool TlakovaZkouska { get; set; }
    
        public virtual Revize Revize { get; set; }
        public virtual SCProvozu SCProvozu { get; set; }
        public virtual Umisteni Umisteni { get; set; }
    }
}
