//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VST_sprava_servisu
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class SCProvozu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCProvozu()
        {
            this.RevizeSC = new HashSet<RevizeSC>();
            this.ServisniZasahPrvek = new HashSet<ServisniZasahPrvek>();
        }
    
        public int Id { get; set; }
        [Display(Name = "Provoz")]
        public int ProvozId { get; set; }
        [Display(Name = "Sériové èíslo")]
        public int SerioveCisloId { get; set; }
        [Display(Name = "Status")]
        public int StatusId { get; set; }
        [Required, Column(TypeName = "Date"), DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}"), Display(Name = "Datum pøiøazení")]
        public System.DateTime DatumPrirazeni { get; set; }
        [Required, Column(TypeName = "Date"), DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}"), Display(Name = "Datum poslední zmìny")]
        public Nullable<System.DateTime> DatumPosledniZmeny { get; set; }
        [Column(TypeName = "Date"), DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}"), Display(Name = "Datum výmìny")]
        public Nullable<System.DateTime> DatumVymeny { get; set; }
        [Display(Name = "Umístìní")]
        public Nullable<int> Umisteni { get; set; }
        [Column(TypeName = "Date"), DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}"), Display(Name = "Poslední revize")]
        public Nullable<System.DateTime> DatumRevize { get; set; }
        [Column(TypeName = "Date"), DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}"), Display(Name = "Poslední výmìna baterie")]
        public Nullable<System.DateTime> DatumBaterie { get; set; }
        [Column(TypeName = "Date"), DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}"), Display(Name = "Poslení výmìna pyroiniciátorù")]
        public Nullable<System.DateTime> DatumPyro { get; set; }
        [Column(TypeName = "Date"), DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}"), Display(Name = "Tlaková zkouška")]
        public Nullable<System.DateTime> DatumTlkZk { get; set; }
        [Display(Name = "Lokace prvku")]
        public string Lokace { get; set; }
        [Display(Name = "Znaèení prvku")]
        public string Znaceni { get; set; }
        [Display(Name = "Provìøit prvek?")]
        public bool Proverit { get; set; }
        public bool Baterie { get; set; }
        [Display(Name = "Použitá baterie")]
        public Nullable<int> BaterieArtikl { get; set; }
        [Display(Name = "Upravená perioda revize [m]")]
        public Nullable<int> UpravenaPeriodaRevize { get; set; }
        [Display(Name = "Ukonèení záruky")]
        public Nullable<System.DateTime> UkonceniZaruky { get; set; }

        public virtual Provoz Provoz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RevizeSC> RevizeSC { get; set; }
        public virtual SerioveCislo SerioveCislo { get; set; }
        public virtual Status Status { get; set; }
        public virtual Umisteni Umisteni1 { get; set; }
        public virtual Artikl Artikl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VymenyLahvi> VymenyLahvi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VymenyLahvi> VymenyLahvi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServisniZasahPrvek> ServisniZasahPrvek { get; set; }

        [Display(Name = "Upravená perioda pyro [m]")]
        public Nullable<int> UpravenaPeriodaPyro { get; set; }
        [Display(Name = "Upravená perioda baterie [m]")]
        public Nullable<int> UpravenaPeriodaBaterie { get; set; }
        [Display(Name = "Upravená perioda Tlakové zkoušky [m]")]
        public Nullable<int> UpravenaPeriodaTlkZk { get; set; }

        public Nullable<System.DateTime> DatumRevizeTlakoveNadoby { get; set; }
        public Nullable<System.DateTime> DatumVnitrniRevizeTlakoveNadoby { get; set; }
        public Nullable<int> UpravenaPeriodaRevizeTlakoveNadoby { get; set; }
        public Nullable<int> UpravenaPeriodaVnitrniRevizeTlakoveNadoby { get; set; }

        public string SCLahve { get; set; }
    }
}
