//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VST_sprava_servisu
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCProvozu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCProvozu()
        {
            this.RevizeSC = new HashSet<RevizeSC>();
        }
    
        public int Id { get; set; }
        public int ProvozId { get; set; }
        public int SerioveCisloId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime DatumPrirazeni { get; set; }
        public Nullable<System.DateTime> DatumPosledniZmeny { get; set; }
        public Nullable<System.DateTime> DatumVymeny { get; set; }
        public Nullable<int> Umisteni { get; set; }
        public Nullable<System.DateTime> DatumRevize { get; set; }
        public Nullable<System.DateTime> DatumBaterie { get; set; }
        public Nullable<System.DateTime> DatumPyro { get; set; }
        public Nullable<System.DateTime> DatumTlkZk { get; set; }
        public string Lokace { get; set; }
        public string Znaceni { get; set; }
    
        public virtual Provoz Provoz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RevizeSC> RevizeSC { get; set; }
        public virtual SerioveCislo SerioveCislo { get; set; }
        public virtual Status Status { get; set; }
        public virtual Umisteni Umisteni1 { get; set; }
    }
}
