//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VST_sprava_servisu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServisniZasah
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServisniZasah()
        {
            this.ServisniZasahPrvek = new HashSet<ServisniZasahPrvek>();
        }
    
        public int Id { get; set; }
        public int ZakaznikID { get; set; }
        public int ProvozId { get; set; }
        public int UmisteniId { get; set; }
        public System.DateTime DatumVyzvy { get; set; }
        public System.DateTime DatumVznikuPoruchy { get; set; }
        public System.DateTime DatumZasahu { get; set; }
        public System.DateTime DatumOdstraneni { get; set; }
        public string Odkud { get; set; }
        public string Kam { get; set; }
        public string Zpět { get; set; }
        public Nullable<double> Km { get; set; }
        public Nullable<int> VozidloId { get; set; }
        public Nullable<double> CestaCelkem { get; set; }
        public Nullable<double> PraceHod { get; set; }
        public Nullable<double> PraceSazba { get; set; }
        public Nullable<int> Pracelidi { get; set; }
        public Nullable<double> PraceCelkem { get; set; }
        public Nullable<double> Celkem { get; set; }
        public bool Reklamace { get; set; }
        public bool PoruseniZarucnichPodminek { get; set; }
        public string Mena { get; set; }
    
        public virtual Provoz Provoz { get; set; }
        public virtual Umisteni Umisteni { get; set; }
        public virtual Vozidlo Vozidlo { get; set; }
        public virtual Zakaznik Zakaznik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServisniZasahPrvek> ServisniZasahPrvek { get; set; }
    }
}
