//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VST_sprava_servisu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServisniZasahPrvek
    {
        public int Id { get; set; }
        public int ServisniZasahId { get; set; }
        public int SCProvozuID { get; set; }
        public int PoruchaID { get; set; }
        public Nullable<int> ArtiklID { get; set; }
        public Nullable<double> Pocet { get; set; }
        public Nullable<double> CenaZaKus { get; set; }
        public Nullable<double> CenaCelkem { get; set; }
    
        public virtual Artikl Artikl { get; set; }
        public virtual Porucha Porucha { get; set; }
        public virtual SCProvozu SCProvozu { get; set; }
        public virtual ServisniZasah ServisniZasah { get; set; }
    }
}
