//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VST_sprava_servisu
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkupinaArtiklu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SkupinaArtiklu()
        {
            this.Artikl = new HashSet<Artikl>();
        }
    
        public int Id { get; set; }
        public string Skupina { get; set; }
        public bool Revize { get; set; }
        public string PeriodaRevize { get; set; }
        public bool TlakovaZk { get; set; }
        public string PeriodaTlakovaZk { get; set; }
        public bool VymenaBaterie { get; set; }
        public string PeriodaBaterie { get; set; }
        public string ArtiklBaterieSAP { get; set; }
        public bool VymenaPyro { get; set; }
        public string PeriodaPyro { get; set; }
        public string ArtoklPyro { get; set; }
        public Nullable<int> PoradiZobrazeni { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Artikl> Artikl { get; set; }
    }
}
