//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VST_sprava_servisu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Umisteni
    {
        public int Id { get; set; }
        public int ProvozId { get; set; }
        public string NazevUmisteni { get; set; }
    
        public virtual Provoz Provoz { get; set; }
    }
}
