//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VST_sprava_servisu
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Umisteni
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Umisteni()
        {
            this.SCProvozu = new HashSet<SCProvozu>();
            this.RevizeSC = new HashSet<RevizeSC>();
            this.Revize = new HashSet<Revize>();
        }
    
        public int Id { get; set; }
        [Display(Name = "Provoz")]
        public int ProvozId { get; set; }
        [Display(Name = "Název technologie")]
        public string NazevUmisteni { get; set; }
        [Display(Name = "Samostatné revize technologie")]
        public bool SamostatnaRevize { get; set; }
        [Display(Name = "Ukonèení záruky")]
        public Nullable<System.DateTime> UkonceniZaruky { get; set; }

        public virtual Provoz Provoz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCProvozu> SCProvozu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RevizeSC> RevizeSC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Revize> Revize { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServisniZasah> ServisniZasah { get; set; }
    }
}
