//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VST_sprava_servisu
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class VymenyLahvi
    {
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public int SCProvozuPuvodni { get; set; }
        public int SCProvozuNova { get; set; }
        public string SCLahve { get; set; }
        public System.DateTime DatumVymeny { get; set; }
        public int Revize { get; set; }
    
        public virtual SCProvozu SCProvozu { get; set; }
        public virtual SCProvozu SCProvozu1 { get; set; }
        public virtual Revize Revize1 { get; set; }
    }
}
