//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VST_sprava_servisu
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Zakaznik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakaznik()
        {
            this.DIC = "20";
            this.Provoz = new HashSet<Provoz>();
            this.KontakniOsoba = new HashSet<KontakniOsoba>();
        }
    
        public int Id { get; set; }
        [Display(Name = "Název zákazníka")]
        public string NazevZakaznika { get; set; }
        [Display(Name = "SAP kód")]
        public string KodSAP { get; set; }
        [Display(Name = "Region")]
        public int RegionId { get; set; }
        [Display(Name = "IÈ")]
        public string IC { get; set; }
        [Display(Name = "DIÈ")]
        public string DIC { get; set; }
        public string Telefon { get; set; }
        public string Kontakt { get; set; }
        public string Email { get; set; }
        [Display(Name = "Jazyk")]
        public int JazykId { get; set; }
        public string Adresa { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual Jazyk Jazyk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Provoz> Provoz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KontakniOsoba> KontakniOsoba { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServisniZasah> ServisniZasah { get; set; }
    }
}
