//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VST_sprava_servisu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaznik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakaznik()
        {
            this.DIC = "20";
            this.Provoz = new HashSet<Provoz>();
        }
    
        public int Id { get; set; }
        public string NazevZakaznika { get; set; }
        public string KodSAP { get; set; }
        public int RegionId { get; set; }
        public string IC { get; set; }
        public string DIC { get; set; }
        public string Telefon { get; set; }
        public string Kontakt { get; set; }
        public string Email { get; set; }
        public int JazykId { get; set; }
        public string Adresa { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual Jazyk Jazyk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Provoz> Provoz { get; set; }
    }
}
